content: dev delight:
- '.github/*'
- '.github/**/*'

content: documentation:
- 'docs/*'
- 'docs/**/*'
- 'README.md'
- 'THIRD_PARTY_SOFTWARES.md'

content: game:
- 'common/*'
- 'common/**/*'
- 'scenes/*'
- 'scenes/**/*'
- 'project.godot'