name: GDScript lint check

on: [push]

# References
# How to fail: https://stackoverflow.com/questions/57903836/how-to-fail-a-job-in-github-actions
# Base script: https://github.com/actions/starter-workflows/blob/main/ci/pylint.yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 'gdtoolkit==3.*' -q
    - name: Running GDToolkit lint analysis
      run: |
        gdlint common scenes